// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgaikirzhmvlgztotqcf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnYWlraXJ6aG12bGd6dG90cWNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYzMTE0NjUsImV4cCI6MjA1MTg4NzQ2NX0.ff4CPu_L1ERG8qujwqFcR5SxfVtN3yRsMw1AJk93ijs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);